### ISSUE TITLE
Use bootstrap form-groups, input classes, etc.

### ISSUE THREAD

**Issue by abacon** [amp5/Ikura#3]
This means where now you're using `<br>` to space things, instead you should make use of the spacing built into bootstrap's [`.form-group`](http://getbootstrap.com/css/#forms-example), etc classes.

What this basically looks like:

``` html
  <div class="form-group">
    <label for="card1_name[]">Card name:</label> <input type="text" name="card1_name[]" value="ksbgsakbg" class="name form-input" id="name" required="">
  </div>
```

**Comment by amp5** [comment]
Thanks @abacon , my forms look so much better now :smile:
